export const AnimeData = [
    {
        id: "1",
        name: "Biệt đội lính cứu hỏa",
        enName: "Fire Force",
        bgImage: "/images/poster-horizontal.png",
       image: "/images/poster-vertical-1.png",
       imdb: "7.0",
       age: "T16",
       release: "2025",
       part: "1",
       episode: 12,
       genres: [
         {id: "1", name:"Bí ẩn"}, 
         {id: "2", name:"Hài hước"}, 
         {id: "3", name:"Lãng mạn"}, 
         {id: "4", name:"Hài hước"}, 
         {id: "5", name:"Lãng mạn"}
       ],
       description: `Năm 198 của Kỷ nguyên Mặt trời ở Tokyo, các đội cứu hỏa đặc biệt đang chiến đấu chống lại một hiện tượng gọi là sự đốt cháy tự phát của con người, 
                    nơi con người bị biến thành địa ngục sống gọi là "Địa ngục". Trong khi các Địa ngục là trường hợp đốt 
                    cháy tự phát của con người thế hệ đầu tiên, các thế hệ sau có khả năng điều khiển ngọn lửa trong khi 
                    vẫn giữ được hình dạng con người. Shinra Kusakabe, một thanh niên có biệt danh Dấu chân ác quỷ vì 
                    khả năng đốt cháy đôi chân của anh ta theo ý muốn, gia nhập Công ty hỏa lực đặc biệt 8, bao gồm những 
                    người dùng ngọn lửa khác khi họ làm việc để dập tắt mọi địa ngục mà họ gặp phải. Khi một phe đang tạo 
                    ra Infeals xuất hiện, Shira bắt đầu phát hiện ra sự thật đằng sau một đám cháy bí ẩn gây ra cái chết 
                    của gia đình anh mười hai năm trước.`,
    },
    {
        id: "2",
        name: "Marvel",
        enName: "Marvel",
        bgImage: "/images/poster-horizontal.png",
       image: "/images/poster-vertical-2.png",
       imdb: "7.0",
       age: "T16",
       release: "2025",
       part: "1",
       episode: 12,
       genres: [
         {id: "1", name:"Bí ẩn"}, 
         {id: "2", name:"Hài hước"}, 
         {id: "3", name:"Lãng mạn"}, 
         {id: "4", name:"Hài hước"}, 
         {id: "5", name:"Lãng mạn"}
       ],
       description: "Bí ẩn àdsfdsafdsfsdf",
    },
    {
        id: "3",
        name: "Marvel",
        enName: "Marvel",
        bgImage: "/images/poster-horizontal.png",
       image: "/images/poster-vertical-1.png",
       imdb: "7.0",
       age: "T16",
       release: "2025",
       part: "1",
       episode: 12,
       genres: [
        {id: "1", 
            name:"Bí ẩn"}, 
        {id: "2", 
            name:"Hài hước"}, 
        {id: "3", 
            name:"Lãng mạn"}, 
        {id: "4", 
            name:"Hài hước"}, 
        {id: "5", 
            name:"Lãng mạn"}],
       description: "Bí ẩn àdsfdsafdsfsdf",
    },
    {
        id: "4",
        name: "Marvel",
        enName: "Marvel",
        bgImage: "/images/poster-horizontal.png",
       image: "/images/poster-vertical-2.png",
       imdb: "7.0",
       age: "T16",
       release: "2025",
       part: "1",
       episode: 12,
       genres: [{
            id: "1", 
            name:"Bí ẩn"
        }, 
        {
            id: "2", 
            name:"Hài hước"
        }, 
        {
            id: "3", 
            name:"Lãng mạn"
        }, 
        {
            id: "4", 
            name:"Hài hước"
        }, 
        {
            id: "5", 
            name:"Lãng mạn"
        }
    ],
       description: "Bí ẩn àdsfdsafdsfsdf",
    },
    {
        id: "5",
        name: "Marvel",
        enName: "Marvel",
        bgImage: "/images/poster-horizontal.png",
       image: "/images/poster-vertical-1.png",
       imdb: "7.0",
       age: "T16",
       release: "2025",
       part: "1",
       episode: 12,
       genres: [
        {id: "1", 
            name:"Bí ẩn"}, 
        {id: "2", 
            name:"Hài hước"}, 
        {id: "3", 
            name:"Lãng mạn"}, 
        {id: "4", 
            name:"Hài hước"}, 
        {id: "5", 
            name:"Lãng mạn"}
    ],
       description: "Bí ẩn àdsfdsafdsfsdf",
    },
    {
        id: "6",
        name: "Marvel",
        enName: "Marvel",
        bgImage: "/images/poster-horizontal.png",
       image: "/images/poster-vertical-2.png",
       imdb: "7.0",
       age: "T16",
       release: "2025",
       part: "1",
       episode: 12,
       genres: [
        {id: "1", 
            name:"Bí ẩn"}, 
        {id: "2", 
            name:"Hài hước"}, 
        {id: "3", 
            name:"Lãng mạn"}, 
        {id: "4", 
            name:"Hài hước"}, 
        {id: "5", 
            name:"Lãng mạn"}
    ],
       description: "Bí ẩn àdsfdsafdsfsdf",
    },
    {
        id: "7",
        name: "Marvel",
        enName: "Marvel",
        bgImage: "/images/poster-horizontal.png",
       image: "/images/poster-vertical-1.png",
       imdb: "7.0",
       age: "T16",
       release: "2025",
       part: "1",
       episode: 12,
       genres: [
        {id: "1", 
            name:"Bí ẩn"}, 
        {id: "2", 
            name:"Hài hước"}, 
        {id: "3", 
            name:"Lãng mạn"}, 
        {id: "4", 
            name:"Hài hước"}, 
        {id: "5", 
            name:"Lãng mạn"}
    ],
       description: "Bí ẩn àdsfdsafdsfsdf",
    },
    {
        id: "8",
        name: "Marvel",
        enName: "Marvel",
        bgImage: "/images/poster-horizontal.png",
       image: "/images/poster-vertical-2.png",
       imdb: "7.0",
       age: "T16",
       release: "2025",
       part: "1",
       episode: 12,
        genres: [
        {id: "1", 
            name:"Bí ẩn"}, 
        {id: "2", 
            name:"Hài hước"}, 
        {id: "3", 
            name:"Lãng mạn"}, 
        {id: "4", 
            name:"Hài hước"}, 
        {id: "5", 
            name:"Lãng mạn"}
    ],
       description: "Bí ẩn àdsfdsafdsfsdf",
    },
    {
        id: "9",
        name: "Marvel",
        enName: "Marvel",
        bgImage: "/images/poster-horizontal.png",
       image: "/images/poster-vertical-1.png",
       imdb: "7.0",
       age: "T16",
       release: "2025",
       part: "1",
       episode: 12,
       genres: [
        {id: "1", 
            name:"Bí ẩn"}, 
        {id: "2", 
            name:"Hài hước"}, 
        {id: "3", 
            name:"Lãng mạn"}, 
        {id: "4", 
            name:"Hài hước"}, 
        {id: "5", 
            name:"Lãng mạn"}
    ],
       description: "Bí ẩn àdsfdsafdsfsdf",
    },
    {
        id: "10",
        name: "Marvel",
        enName: "Marvel",
        bgImage: "/images/poster-horizontal.png",
       image: "/images/poster-vertical-2.png",
       imdb: "7.0",
       age: "T16",
       release: "2025",
       part: "1",
       episode: 12,
       genres: [
        {id: "1", 
            name:"Bí ẩn"}, 
        {id: "2", 
            name:"Hài hước"}, 
        {id: "3", 
            name:"Lãng mạn"}, 
        {id: "4", 
            name:"Hài hước"}, 
        {id: "5", 
            name:"Lãng mạn"}
    ],
       description: "Bí ẩn àdsfdsafdsfsdf",
    },
    {
        id: "11",
        name: "Marvel",
        enName: "Marvel",
        bgImage: "/images/poster-horizontal.png",
       image: "/images/poster-vertical-1.png",
       imdb: "7.0",
       age: "T16",
       release: "2025",
       part: "1",
       episode: 12,
       genres: [
        {id: "1", 
            name:"Bí ẩn"}, 
        {id: "2", 
            name:"Hài hước"}, 
        {id: "3", 
            name:"Lãng mạn"}, 
        {id: "4", 
            name:"Hài hước"}, 
        {id: "5", 
            name:"Lãng mạn"}
    ],
       description: "Bí ẩn àdsfdsafdsfsdf",
    },
    {
        id: "12",
        name: "Marvel",
        enName: "Marvel",
        bgImage: "/images/poster-horizontal.png",
       image: "/images/poster-vertical-2.png",
       imdb: "7.0",
       age: "T16",
       release: "2025",
       part: "1",
       episode: 12,
       genres: [
         {id: "1", name:"Bí ẩn"}, 
         {id: "2", name:"Hài hước"}, 
         {id: "3", name:"Lãng mạn"}, 
         {id: "4", name:"Hài hước"}, 
         {id: "5", name:"Lãng mạn"}
       ],
       description: "Bí ẩn àdsfdsafdsfsdf",
    },
    {
        id: "13",
        name: "Marvel",
        enName: "Marvel",
        bgImage: "/images/poster-horizontal.png",
       image: "/images/poster-vertical-1.png",
       imdb: "7.0",
       age: "T16",
       release: "2025",
       part: "1",
       episode: 12,
       genres: [
        {id: "1", 
            name:"Bí ẩn"}, 
        {id: "2", 
            name:"Hài hước"}, 
        {id: "3", 
            name:"Lãng mạn"}, 
        {id: "4", 
            name:"Hài hước"}, 
        {id: "5", 
            name:"Lãng mạn"}],
       description: "Bí ẩn àdsfdsafdsfsdf",
    },
    {
        id: "14",
        name: "Marvel",
        enName: "Marvel",
        bgImage: "/images/poster-horizontal.png",
       image: "/images/poster-vertical-2.png",
       imdb: "7.0",
       age: "T16",
       release: "2025",
       part: "1",
       episode: 12,
       genres: [
        {id: "1", 
            name:"Bí ẩn"}, 
        {id: "2", 
            name:"Hài hước"}, 
        {id: "3", 
            name:"Lãng mạn"}, 
        {id: "4", 
            name:"Hài hước"}, 
        {id: "5", 
            name:"Lãng mạn"}],
       description: "Bí ẩn àdsfdsafdsfsdf",
    },
    {
        id: "15",
        name: "Marvel",
        enName: "Marvel",
        bgImage: "/images/poster-horizontal.png",
       image: "/images/poster-vertical-1.png",
       imdb: "7.0",
       age: "T16",
       release: "2025",
       part: "1",
       episode: 12,
       genres: [
        {id: "1", 
            name:"Bí ẩn"}, 
        {id: "2", 
            name:"Hài hước"}, 
        {id: "3", 
            name:"Lãng mạn"}, 
        {id: "4", 
            name:"Hài hước"}, 
        {id: "5", 
            name:"Lãng mạn"}],
       description: "Bí ẩn àdsfdsafdsfsdf",
    },
]